import assert from "node:assert/strict";
import { createServer } from "vite";
import { createRequire } from "node:module";
import { homedir } from "node:os";
import { join } from "node:path";
const require = createRequire(join(homedir(), ".cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json"));
const { chromium } = require("playwright");
const server = await createServer({ configFile: false, cacheDir: "node_modules/.vite/framing", esbuild: { jsx: "automatic" }, optimizeDeps: { noDiscovery: true, include: ["react", "react-dom/client", "react/jsx-runtime", "react/jsx-dev-runtime", "lucide-react", "lucide-react/dynamicIconImports"] }, server: { port: 5220, host: "127.0.0.1" }, plugins: [{ name: "fixture", configureServer(s) { s.middlewares.use("/fixture", async (_req, res) => { res.setHeader("Content-Type", "text/html"); res.end(await s.transformIndexHtml("/fixture", '<div id="root"></div><style>:root{--his-accent:#d516e9}</style><script type="module" src="/tests/image-framing.fixture.tsx"></script>')); }); } }] });
await server.listen(); let browser;
try {
  browser = await chromium.launch({ channel: "msedge", headless: true });
  const page = await browser.newPage({ viewport: { width: 1200, height: 950 } }); page.setDefaultTimeout(60000);
  const errors = []; page.on("pageerror", (e) => errors.push(e.message));
  await page.addInitScript(() => { window.urlCreations = 0; const make = URL.createObjectURL.bind(URL); URL.createObjectURL = (...args) => { window.urlCreations++; return make(...args); }; });
  await page.goto("http://127.0.0.1:5220/fixture", { waitUntil: "domcontentloaded" });
  console.log("Framing fixture ready");
  const frame = page.locator(".his-image-framing__frame");
  const apply = () => page.getByRole("button", { name: "Aplicar", exact: true }).click();
  const choose = async (name) => { await page.getByRole("dialog").getByTitle(name, { exact: true }).click(); await frame.locator("img").waitFor(); await page.waitForFunction(() => document.querySelector('.his-image-framing__actions button:last-child')?.disabled === false); };
  const zoom = page.getByRole("slider", { name: "Zoom", exact: true });
  const composition = (locator) => locator.evaluate((f) => { const r = f.getBoundingClientRect(), i = f.querySelector("img").getBoundingClientRect(); return [(i.left - r.left) / r.width, (i.top - r.top) / r.height, i.width / r.width, i.height / r.height]; });
  const compare = (a, b) => a.forEach((n, i) => assert.ok(Math.abs(n - b[i]) < .015, `same composition ${a} / ${b}`));
  const drag = async (dx, dy) => { const r = await frame.boundingBox(); await page.mouse.move(r.x + r.width / 2, r.y + r.height / 2); await page.mouse.down(); await page.mouse.move(r.x + r.width / 2 + dx, r.y + r.height / 2 + dy, { steps: 15 }); await page.mouse.up(); };
  await page.locator("#pick-vault").click(); await choose("wide");
  const r = await frame.boundingBox(); assert.ok(Math.abs(r.width / r.height - 1) < .001);
  assert.equal(await frame.locator(".his-image-framing__mask").evaluate((e) => getComputedStyle(e).borderTopColor), "rgb(213, 22, 233)");
  const before = await page.evaluate(() => ({ renders: window.parentRenders, setting: window.savedVault(), urls: window.urlCreations }));
  await zoom.focus(); await page.keyboard.press("End"); await drag(90, -30);
  assert.deepEqual(await page.evaluate(() => ({ renders: window.parentRenders, setting: window.savedVault(), urls: window.urlCreations })), before, "drag / zoom do not update nodes, save settings or recreate URLs");
  const vaultPreview = await composition(frame); await apply();
  await page.waitForFunction(() => window.state.vaultPresentation?.zoom === 5);
  compare(vaultPreview, await composition(page.locator("#vault .his-presented-image")));
  const savedVault = await page.evaluate(() => window.savedVault()); assert.ok(JSON.parse(savedVault).presentation);
  await page.locator("#vault").click(); await frame.waitFor(); assert.equal(await zoom.inputValue(), "5"); compare(vaultPreview, await composition(frame));
  await zoom.focus(); await page.keyboard.press("Home"); await drag(-100, 0);
  await page.getByRole("button", { name: "Cancelar", exact: true }).click(); await page.getByRole("button", { name: "X", exact: true }).count();
  await page.getByRole("dialog").getByRole("button", { name: "Cerrar", exact: true }).click();
  assert.equal(await page.evaluate(() => window.savedVault()), savedVault, "cancel leaves the saved transform unchanged");
  // Real cover aspect comes from the actual CSS measurement, never a fixed 16:9.
  await page.locator('.page-node-header__actions button[aria-label="Elegir portada"]').click(); await choose("tall");
  const coverRatio = (await frame.boundingBox()); const ratio = coverRatio.width / coverRatio.height;
  assert.ok(Math.abs(ratio - 16 / 9) > .1);
  await zoom.focus(); for (let i = 0; i < 40; i++) await page.keyboard.press("ArrowRight"); await drag(0, 25);
  const coverPreview = await composition(frame); await apply();
  await page.locator(".page-node-header__cover.has-image .his-presented-image").waitFor();
  compare(coverPreview, await composition(page.locator(".page-node-header__cover.has-image .his-presented-image")));
  const cover = page.locator(".page-node-header__cover.has-image"); const coverRect = await cover.boundingBox(); assert.ok(Math.abs(coverRect.width / coverRect.height - ratio) < .01);
  const coverSaved = await page.evaluate(() => window.state.pageMeta.coverPresentation);
  await cover.click(); await frame.waitFor(); assert.ok(Math.abs(Number(await zoom.inputValue()) - coverSaved.zoom) < .001); compare(coverPreview, await composition(frame));
  await page.getByRole("dialog").getByRole("button", { name: "Cerrar", exact: true }).click();
  await page.setViewportSize({ width: 900, height: 950 });
  await cover.click(); await frame.waitFor(); const resizedPreview = await composition(frame);
  await page.getByRole("dialog").getByRole("button", { name: "Cerrar", exact: true }).click();
  compare(resizedPreview, await composition(cover.locator(".his-presented-image")));
  await page.locator('.page-node-header__actions button[aria-label="Elegir icono"]').click(); await choose("wide");
  await zoom.focus(); for (let i = 0; i < 20; i++) await page.keyboard.press("ArrowRight"); await drag(30, 0);
  const iconPreview = await composition(frame); await apply(); await page.locator(".page-node-header__icon.his-presented-image").waitFor();
  compare(iconPreview, await composition(page.locator(".page-node-header__icon.his-presented-image")));
  assert.ok(await page.evaluate(() => window.originalUnchanged()), "original bytes remain unchanged");
  assert.ok(await page.evaluate(() => window.state.nodes.find((n) => n.id === "page").content.endsWith("<p>Keep this text</p>")));
  await page.reload(); await page.locator(".page-node-header__icon.his-presented-image").waitFor();
  compare(iconPreview, await composition(page.locator(".page-node-header__icon.his-presented-image")));
  assert.deepEqual(await page.evaluate(() => window.state.pageMeta.coverPresentation), coverSaved);
  await page.locator('.page-node-header__actions button[aria-label="Elegir icono"]').click(); await page.getByRole("button", { name: "Emojis", exact: true }).click(); await page.locator(".node-visual-picker__grid--emojis button").first().click(); assert.equal(await frame.count(), 0); assert.equal(await page.getByRole("dialog").count(), 0);
  await page.locator('.page-node-header__actions button[aria-label="Elegir icono"]').click(); await page.getByRole("button", { name: "Iconos", exact: true }).click(); await page.locator(".node-visual-picker__grid--icons button").first().click(); assert.equal(await frame.count(), 0); assert.equal(await page.getByRole("dialog").count(), 0);
  // Imported originals remain in the library even when framing is cancelled.
  await page.locator("#pick-vault").click();
  const png = await page.evaluate(async () => Array.from(new Uint8Array(await (await fetch(document.querySelector('.page-image-picker__gallery img').src)).arrayBuffer())));
  await page.getByRole("dialog").locator('input[type="file"]').setInputFiles({ name: "Original.png", mimeType: "image/png", buffer: Buffer.from(png) }); await frame.waitFor();
  await page.getByRole("button", { name: "Cancelar", exact: true }).click(); assert.equal(await page.getByRole("dialog").getByTitle("Original.png", { exact: true }).count(), 1);
  assert.ok(await page.evaluate(() => window.originalUnchanged()));
  assert.deepEqual(errors, []);
  console.log("Framing: square vault/icon, measured responsive cover, drag/zoom limits, shared geometry, cancel/X, reopening, original bytes, semantic bypass, uploads and zero per-frame persistence/URL creation passed.");
} finally { await browser?.close(); await server.close(); }
