import { createServer } from 'vite';
import { createRequire } from 'node:module';
import { homedir } from 'node:os';
import { join } from 'node:path';
import assert from 'node:assert/strict';
const require = createRequire(join(homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json'));
const { chromium } = require('playwright');
const server = await createServer({ server: { host: '127.0.0.1', port: 1432, strictPort: true } });
await server.listen();
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
 const page = await browser.newPage({ viewport: { width: 1227, height: 690 } });
 page.on('console', message => { if (message.type() === 'error') console.log('CONSOLE', message.text()); });
 page.on('pageerror', error => console.log('PAGE ERROR', error.message));
 await page.goto('http://127.0.0.1:1432/');
 await page.locator('.home-action--quick-dev button').click({ timeout: 120000 });
 await page.locator('[data-node-id]').first().waitFor({ timeout: 120000 });
 const snapshot = () => page.evaluate(async () => (await import('/src/project/browserDevBackend.ts')).listBrowserDevNodes());
 await page.locator('.context-toolbar button').first().click();
 await page.locator('.lore-add-dialog__choices button').last().click();
 await page.locator('.node-creation').waitFor();
 await page.screenshot({ path: 'C:/Users/Matias/Documents/COSAS_DE_HIS/H.I.S.Future/hisfuture/docs/node-creation-wide.png' });
 const before = await snapshot();
 assert.equal(await page.getByRole('button', { name: 'Crear Nodo en Lore', exact: true }).isDisabled(), true);
 await page.locator('.node-creation input').first().fill('Cancel test');
 await page.keyboard.press('Escape');
 assert.deepEqual(await snapshot(), before);
 const chooseNode = async (index, id) => {
   await page.locator('.node-creation__node-choice').nth(index).click();
   if (index === 0 && id) await page.screenshot({ path: 'C:/Users/Matias/Documents/COSAS_DE_HIS/H.I.S.Future/hisfuture/docs/node-existing-picker.png' });
   if (id) { await page.locator(`.existing-node-picker input[type=radio][value="${id}"]`).check(); await page.locator('.existing-node-picker footer button').first().click(); }
   else await page.locator('.existing-node-picker footer button').nth(1).click();
 };
 const reopen = async () => { await page.locator('.context-toolbar button').first().click(); await page.locator('.lore-add-dialog__choices button').last().click(); await page.locator('.node-creation').waitFor(); };
 await reopen();
 await page.mouse.click(100, 300);
 assert.equal(await page.locator('.node-creation').count(), 0);
 await reopen();
 await page.getByRole('button', { name: 'Elegir Plantilla', exact: true }).click();
 await page.getByText('No hay plantillas disponibles.', { exact: true }).waitFor();
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('.node-creation').count(), 1);
 await page.locator('.node-creation input').first().fill('Node creation Lore');
 await page.getByRole('button', { name: 'Crear Nodo en Lore', exact: true }).click();
 await page.locator('.node-creation').waitFor({ state: 'detached' });
 const lore = (await snapshot()).find(n => n.name === 'Node creation Lore');
 assert.ok(lore); assert.equal(lore.parentId, null);
 assert.ok(!lore.content.includes('Opcional'));
 await page.evaluate(async () => { await (await import('/src/tags/repository.ts')).createTag({ name: 'Real tag', color: '#4DD8C0' }); });
 await reopen();
 await page.locator('.node-creation input').first().fill('Parent and tags');
 await page.locator('.node-creation input').nth(1).fill('Real description');
 await chooseNode(0, lore.id);
 await page.getByRole('button', { name: '#Real tag', exact: true }).click();
 await page.getByRole('button', { name: 'Crear Nodo en Lore', exact: true }).click();
 await page.locator('.node-creation').waitFor({ state: 'detached' });
 const tagged = (await snapshot()).find(n => n.name === 'Parent and tags');
 assert.equal(tagged.parentId, lore.id);
 assert.equal(await page.evaluate(async id => (await import('/src/tags/repository.ts')).getNodeTags(id).then(tags => tags[0].name), tagged.id), 'Real tag');
 assert.equal(await page.evaluate(async content => (await import('/src/utils/pageMeta.ts')).getPageMeta(content).description, tagged.content), 'Real description');
 await reopen();
 await chooseNode(1, tagged.id);
 await page.getByRole('button', { name: 'Cancelar', exact: true }).last().click();
 assert.equal((await snapshot()).find(n => n.id === tagged.id).parentId, lore.id);
 await chooseNode(1, tagged.id);
 await page.getByRole('button', { name: 'Usar @mención', exact: true }).click();
 assert.equal((await snapshot()).find(n => n.id === tagged.id).parentId, lore.id);
 await chooseNode(1, tagged.id);
 await page.getByRole('button', { name: 'Mover aquí', exact: true }).click();
 await page.locator('.node-creation input').first().fill('New parent');
 await page.getByRole('button', { name: 'Crear Nodo en Lore', exact: true }).click();
 await page.locator('.node-creation').waitFor({ state: 'detached' });
 const moved = await snapshot();
 assert.equal(moved.find(n => n.id === tagged.id).parentId, moved.find(n => n.name === 'New parent').id);
 await reopen();
 await page.setViewportSize({ width: 390, height: 500 });
 await page.screenshot({ path: 'C:/Users/Matias/Documents/COSAS_DE_HIS/H.I.S.Future/hisfuture/docs/node-creation-small.png' });
 assert.equal(await page.locator('.node-creation').evaluate(el => el.scrollWidth > el.clientWidth), false);
 await page.locator('.node-creation input').first().fill('Node creation Vault');
 await page.getByRole('button', { name: 'Crear Nodo en Baúl', exact: true }).click();
 await page.locator('.node-creation').waitFor({ state: 'detached' });
 const vault = (await snapshot()).find(n => n.name === 'Node creation Vault');
 assert.ok(vault);
 assert.ok(await page.evaluate(async id => JSON.parse((await import('/src/project/browserDevBackend.ts')).getBrowserDevSetting('loreHiddenIds')).includes(id), vault.id));
 await page.setViewportSize({ width: 1227, height: 690 });
 await page.locator(`[data-node-id="${lore.id}"] .lore-node__add`).click();
 assert.equal(await page.locator('.node-creation__node-choice').first().getAttribute('data-node-id'), lore.id);
 await chooseNode(0, '');
 assert.equal(await page.locator('.node-creation__node-choice').first().getAttribute('data-node-id'), '');
 await page.keyboard.press('Escape');
 await page.getByRole('button', { name: 'Grafo', exact: true }).click();
 await page.locator('.graph-view canvas').waitFor();
 await page.locator('.graph-view canvas').click({ button: 'right', position: { x: 25, y: 80 } });
 await page.locator('.his-context-menu button').filter({ hasText: 'Crear' }).click();
 await page.locator('.node-creation').waitFor();
 assert.equal(await page.locator('.node-creation__node-choice').first().getAttribute('data-node-id'), '');
 await page.locator('.node-creation input').first().fill('Created from graph');
 await page.getByRole('button', { name: 'Crear Nodo en Lore', exact: true }).click();
 await page.locator('.node-creation').waitFor({ state: 'detached' });
 assert.ok((await snapshot()).some(n => n.name === 'Created from graph'));
 await page.getByRole('button', { name: 'Ajustes del proyecto', exact: true }).click();
 await page.locator('.project-settings__field select').first().selectOption('tarea');
 await page.locator('.project-settings__field select').nth(1).selectOption('en');
 await page.getByRole('button', { name: 'Project settings', exact: true }).click();
 await reopen();
 assert.equal(await page.locator('.node-creation__types button[aria-pressed=true]').getAttribute('title'), 'Task Node');
 await page.getByRole('heading', { name: 'Create a new Node', exact: true }).waitFor();
 await page.getByRole('button', { name: 'Cancel', exact: true }).click();
 const createType = async (type, name) => {
   await reopen();
   assert.equal(await page.locator('.node-creation__types [data-type=tempo]').count(), 0);
   assert.deepEqual((await page.locator('.node-creation__types button').evaluateAll(elements => elements.map(el => el.dataset.type))).slice(0, 5), ['pagina', 'categoria', 'proyecto', 'imagen', 'video']);
   await page.locator(`.node-creation__types [data-type=${type}]`).click();
   await page.locator('.node-creation input').first().fill(name);
   await page.getByRole('button', { name: 'Create Node in Lore', exact: true }).click();
   await page.locator('.node-creation').waitFor({ state: 'detached' });
   return (await snapshot()).find(n => n.name === name);
 };
 const project = await createType('proyecto', 'Additional project');
 assert.ok(project);
 await page.locator('.editor-content').first().waitFor();
 const calendar1 = await createType('calendario', 'Calendar 1');
 const calendar2 = await createType('calendario', 'Calendar 2');
 assert.ok(calendar1 && calendar2 && calendar1.id !== calendar2.id);
 const image = await createType('imagen', 'Empty image');
 await page.getByRole('button', { name: 'Upload image', exact: true }).waitFor();
 const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jY1kAAAAASUVORK5CYII=', 'base64');
 await page.locator('.image-node-view__empty input[type=file]').setInputFiles({ name: 'adopted.png', mimeType: 'image/png', buffer: png });
 await page.locator('.image-node-view__preview').waitFor();
 await page.evaluate(async () => { window.creationTestBackend = await import('/src/project/browserDevBackend.ts'); });
 await page.waitForFunction(id => window.creationTestBackend.listBrowserDevNodes().find(n => n.id === id)?.content.includes('hisfuture-image-resource'), image.id);
 const imageResource = await page.evaluate(async id => { const n = (await import('/src/project/browserDevBackend.ts')).listBrowserDevNodes().find(n => n.id === id); return (await import('/src/utils/imageResource.ts')).getImageResourceDescriptor(n.content, n.name); }, image.id);
 assert.equal(imageResource.fileName, 'adopted.png'); assert.equal(imageResource.fileSize, png.length); assert.equal(imageResource.mimeType, 'image/png'); assert.ok(imageResource.hash);
 const pdfNode = await createType('pdf', 'Empty PDF');
 await page.getByRole('button', { name: 'Upload PDF', exact: true }).waitFor();
 let pdf = '%PDF-1.4\n'; const offsets = [0];
 const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] >>'];
 objects.forEach((body, i) => { offsets.push(Buffer.byteLength(pdf)); pdf += `${i + 1} 0 obj\n${body}\nendobj\n`; });
 const xref = Buffer.byteLength(pdf); pdf += 'xref\n0 4\n0000000000 65535 f \n' + offsets.slice(1).map(n => `${String(n).padStart(10, '0')} 00000 n \n`).join('') + `trailer\n<< /Size 4 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
 await page.locator('.pdf-node-view__empty input[type=file]').setInputFiles({ name: 'adopted.pdf', mimeType: 'application/pdf', buffer: Buffer.from(pdf) });
 await page.waitForFunction(id => window.creationTestBackend.listBrowserDevNodes().find(n => n.id === id)?.name === 'adopted.pdf', pdfNode.id);
 await page.locator('.pdf-viewer').waitFor();
 console.log('PASS: existing-node picker, previous creation flows, new types, multiple calendars, image metadata adoption, PDF upload');
} finally { await browser.close(); await server.close(); }
