import assert from "node:assert/strict";
import { createServer } from "vite";
import { createRequire } from "node:module";
import { join } from "node:path";
import { homedir } from "node:os";
const require = createRequire(join(homedir(), ".cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json"));
const { chromium } = require("playwright");
const server = await createServer({ configFile: false, cacheDir: "node_modules/.vite/vault-image", esbuild: { jsx: "automatic" }, optimizeDeps: { noDiscovery: true, include: ["react", "react-dom/client", "react/jsx-runtime", "react/jsx-dev-runtime", "lucide-react", "lucide-react/dynamicIconImports"] }, server: { host: "127.0.0.1", port: 5219 }, plugins: [{ name: "fixture", configureServer(s) { s.middlewares.use("/fixture", async (_req, res) => { res.setHeader("Content-Type", "text/html"); res.end(await s.transformIndexHtml("/fixture", '<div id="root"></div><script type="module" src="/tests/vault-image.fixture.tsx"></script>')); }); } }] });
await server.listen();
let browser;
try {
  browser = await chromium.launch({ channel: "msedge", headless: true });
  for (const mode of ["", "?resource=1"]) {
  const page = await browser.newPage();
  await page.addInitScript(() => { window.urlCreations = 0; const original = URL.createObjectURL.bind(URL); URL.createObjectURL = (...args) => { window.urlCreations++; return original(...args); }; });
  const errors = []; page.on("pageerror", (e) => errors.push(e.message));
  page.setDefaultTimeout(60000);
  await page.goto(`http://127.0.0.1:5219/fixture${mode}`, { waitUntil: "domcontentloaded" });
  console.log("Fixture loaded");
  await page.locator("#avatar img").waitFor();
  const initialCreations = await page.evaluate(() => window.urlCreations);
  const first = await page.locator("#avatar img").getAttribute("src");
  await page.evaluate(() => { window.sources = []; window.originalImage = document.querySelector("#avatar img"); });
  await page.locator("#editor").pressSequentially("abcdefghi".repeat(10), { delay: 15 });
  assert.ok(await page.evaluate(() => window.sources.every((src) => src === window.originalImage.src)));
  assert.ok(await page.evaluate(() => window.originalImage === document.querySelector("#avatar img")));
  await page.locator("#metadata").click();
  assert.equal(await page.locator("#avatar img").getAttribute("src"), first);
  assert.ok(await page.evaluate(() => window.sources.every((src) => src === window.originalImage.src)));
  assert.equal(await page.evaluate(() => window.urlCreations), initialCreations);
  await page.locator("#avatar").click();
  const dialog = page.getByRole("dialog", { name: "Elegir imagen del Baúl", exact: true }); await dialog.waitFor();
  for (const name of ["Emojis", "Iconos", "Unsplash"]) assert.equal(await dialog.getByRole("button", { name, exact: true }).count(), 1);
  await dialog.getByTitle("Segunda", { exact: true }).click();
  await dialog.getByRole("button", { name: "Aplicar", exact: true }).click();
  await page.waitForFunction(() => document.querySelector("#avatar img")?.src.includes("blue"));
  assert.equal(await page.getByRole("dialog").count(), 0);
  assert.equal(await page.locator("#count").textContent(), "3");
  assert.equal(await page.locator("#editor").inputValue(), "abcdefghi".repeat(10));
  await page.evaluate(() => { window.sources = []; });
  await page.locator("#editor").pressSequentially("xyzxyz", { delay: 20 });
  assert.ok(await page.evaluate(() => window.sources.every((src) => src?.includes("blue"))));
  await page.reload(); await page.waitForFunction(() => document.querySelector("#avatar img")?.src.includes("blue"));
  await page.locator("#avatar").click(); await page.getByRole("button", { name: "Quitar imagen del Baúl", exact: true }).click();
  await page.locator("#avatar img").waitFor({ state: "detached" });
  await page.reload(); await page.locator("#avatar").waitFor(); assert.equal(await page.locator("#avatar img").count(), 0);
  await page.locator("#avatar").click();
  await page.getByRole("button", { name: "Emojis", exact: true }).click();
  await page.locator(".node-visual-picker__grid--emojis button").first().click();
  const emoji = await page.locator("#avatar .node-visual--emoji").textContent();
  assert.ok(emoji);
  await page.reload();
  await page.locator("#avatar .node-visual--emoji").waitFor();
  assert.equal(await page.locator("#avatar .node-visual--emoji").textContent(), emoji);
  await page.locator("#avatar").click();
  await page.getByRole("button", { name: "Iconos", exact: true }).click();
  await page.locator(".node-visual-picker__grid--icons button").first().click();
  await page.locator("#avatar svg").waitFor();
  await page.reload(); await page.locator("#avatar svg").waitFor();
  assert.deepEqual(errors, []);
  await page.close();
  }
  console.log("Vault image: typing stability, DOM identity, resource metadata, shared providers, selection, isolation, reopen and removal passed.");
} finally { await browser?.close(); await server.close(); }
