import assert from 'node:assert/strict';
import {createServer} from 'vite';
import {createRequire} from 'node:module';
import {join} from 'node:path';
import {homedir} from 'node:os';
import {mkdir,writeFile,readFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {gzipSync,gunzipSync} from 'node:zlib';
async function readJson(path){const bytes=await readFile(path);return JSON.parse((path.endsWith('.gz')?gunzipSync(bytes):bytes).toString('utf8'));}
const require=createRequire(join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json'));
const {chromium}=require('playwright');const auditPort=Number(process.env.HIS_AUDIT_PORT??5208);
const dir=process.env.HIS_AUDIT_OUTPUT??'tests/editor-audit/results';await mkdir(dir,{recursive:true});
const arg=(name,fallback)=>process.argv.find(x=>x.startsWith(`--${name}=`))?.split('=').slice(1).join('=')??fallback;
const rng=seed=>()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};
async function hashes(){const result={};async function walk(p){for(const d of await readdir(p,{withFileTypes:true})){const q=`${p}/${d.name}`;if(d.isDirectory())await walk(q);else result[q]=createHash('sha256').update(await readFile(q)).digest('hex');}}await walk('src');await walk('src-tauri/src');return result;}
const baseline=await hashes();await writeFile(`${dir}/baseline.json`,JSON.stringify(baseline,null,2));
const server=await createServer({configFile:false,cacheDir:'node_modules/.vite/editor-audit',esbuild:{jsx:'automatic'},optimizeDeps:{noDiscovery:true,include:['react/jsx-dev-runtime','react/jsx-runtime','nspell','react','react-dom','react-dom/client','lucide-react','lucide-react/dynamicIconImports']},server:{port:auditPort,host:'127.0.0.1',strictPort:true},plugins:[{name:'audit',configureServer(s){s.middlewares.use('/audit',async(req,res)=>{res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml('/audit','<div id="root"></div><script type="module" src="/tests/editor-audit/fixture.tsx"></script>'));});}}]});
let browser,page;const errors=[],warnings=[],findings=[],runs=[],regressions=[],properties=[],soak=[];let serial=0;
function failure(id,message){const e=Error(message);e.auditId=id;return e;}
async function reset(html){await page.evaluate(html=>window.audit.reset(html),html);await page.waitForTimeout(35);await page.locator('.editor-content').waitFor();await page.evaluate(()=>getSelection().removeAllRanges());}
async function state(){return page.evaluate(()=>{const e=document.querySelector('.editor-content'),s=getSelection(),r=s.rangeCount?s.getRangeAt(0):null;return {id:document.querySelector('#node').textContent,dom:e.innerHTML,html:window.audit.serializeEditorContent(e),semantic:(()=>{const d=document.createElement('div');d.innerHTML=window.audit.serializeEditorContent(e);d.querySelectorAll('[data-mention-id]').forEach(m=>{m.removeAttribute('title');m.removeAttribute('aria-label');});return d.innerHTML;})(),text:e.textContent,blocks:Array.from(e.children).map(x=>({tag:x.tagName,text:x.textContent,html:x.outerHTML})),scroll:document.querySelector('#scroll').scrollTop,selection:r?{text:s.toString(),collapsed:s.isCollapsed,connected:r.startContainer.isConnected&&r.endContainer.isConnected,belongs:e.contains(r.startContainer)&&e.contains(r.endContainer)}:null};});}
async function select(a){return page.evaluate(a=>{const e=document.querySelector('.editor-content');e.focus({preventScroll:true});const blocks=Array.from(e.querySelectorAll('p,h1,h2,h3,li,blockquote,pre')).filter(x=>!x.closest('[data-editor-ui]')&&!x.closest('[data-mention-id]'));const b=blocks[a.block%blocks.length];if(!b)return null;const texts=[];const w=document.createTreeWalker(b,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('[data-mention-id],[data-editor-ui]')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});while(w.nextNode())texts.push(w.currentNode);if(!texts.length){const t=document.createTextNode('');b.appendChild(t);texts.push(t);}const t=texts[a.textIndex%texts.length||0],len=t.length,start=Math.min(a.start??0,len),end=Math.min(a.end??len,len);const r=document.createRange();r.setStart(t,Math.min(start,end));r.setEnd(t,Math.max(start,end));if(a.cross&&blocks.length>1){const next=blocks[(a.block+1)%blocks.length];if(next.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_PRECEDING)r.setEnd(next,next.childNodes.length);}const s=getSelection();s.removeAllRanges();s.addRange(r);return {text:t.textContent,start:Math.min(start,end),end:Math.max(start,end),blockText:b.textContent,blockIndex:Array.from(e.children).findIndex(x=>x===b||x.contains(b))};},a);}
async function paste(text,html=false){await page.evaluate(({text,html})=>{const e=document.querySelector('.editor-content'),d=new DataTransfer();d.setData(html?'text/html':'text/plain',text);e.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:d}));},{text,html});await page.waitForTimeout(12);}
async function invariant(){const s=await state();if(s.selection&&!s.selection.connected)throw failure('SELECTION_DISCONNECTED','Selection uses detached DOM');if(s.selection&&!s.selection.belongs&&await page.locator('.editor-content').evaluate(e=>e.contains(document.activeElement)))throw failure('SELECTION_WRONG_EDITOR','Focused editor has external Range');if(/data-editor-block-identity=|data-line-selected=|data-line-dragging=|data-editor-ui=/.test(s.html))throw failure('TRANSIENT_PERSISTED','Runtime attributes persist');const ids=await page.locator('.editor-content [data-editor-block-id]').evaluateAll(es=>es.map(e=>e.getAttribute('data-editor-block-id')));if(new Set(ids).size!==ids.length)throw failure('DUPLICATE_BLOCK_ID','Duplicate stable block IDs');const editableMentions=await page.locator('.editor-content .editor-mention').evaluateAll(es=>es.filter(e=>e.contentEditable!=='false').map(e=>({id:e.getAttribute('data-mention-id'),html:e.outerHTML})));if(editableMentions.length)throw failure('ATOMIC_MENTION_EDITABLE',JSON.stringify(editableMentions));if(errors.length)throw failure('UNCAUGHT_JS',errors.at(-1));}
async function action(a){
 if(a.kind==='press'){await page.locator('.editor-content').focus();await page.keyboard.press(a.key);await page.waitForTimeout(60);}
 else if(a.kind==='select'){await select(a);}
 else if(a.kind==='slashListMotif'){await reset('<p><br></p>');await page.locator('.editor-content p').click();await page.keyboard.type('/');await page.locator('[data-picker-menu-item="ul"]').click();await page.keyboard.insertText('Contenido 😀');}
 else if(a.kind==='saveSelectedReload'){const html=(await state()).html;await reset(html);}
 else if(a.kind==='paste'){await select(a);await paste(a.value,a.html);}
 else if(a.kind==='replace'){const before=await state();const selected=await select(a);if(!selected)return;const old=await page.locator('.editor-content').textContent();const prefix=await page.evaluate(()=>{const e=document.querySelector('.editor-content'),r=getSelection().getRangeAt(0).cloneRange();r.selectNodeContents(e);r.setEnd(getSelection().getRangeAt(0).startContainer,getSelection().getRangeAt(0).startOffset);return r.toString();});await paste(a.value,a.html);const actual=await page.locator('.editor-content').textContent();const expected=old.slice(0,prefix.length)+(a.expected??a.value)+old.slice(prefix.length+selected.end-selected.start);if(actual.replace(/\u00a0/g,' ')!==expected.replace(/\u00a0/g,' '))throw failure('PASTE_REPLACEMENT',JSON.stringify({expected,actual}));const after=await state();if(before.blocks.length===after.blocks.length)for(let i=0;i<before.blocks.length;i++){if(before.blocks[i].text!==after.blocks[i].text&&i!==selected.blockIndex)throw failure('UNRELATED_BLOCK_MUTATION',`block ${i} changed`);}}
 else if(a.kind==='key'){await select(a);await page.keyboard.press(a.key);}
 else if(a.kind==='type'){await select({...a,end:a.start});await page.keyboard.insertText(a.value);}
 else if(a.kind==='mark'){await select(a);await page.keyboard.press(a.key);}
 else if(a.kind==='undoRedo'){await page.waitForTimeout(100);const before=(await state()).html;await page.locator('.editor-content').focus();await page.keyboard.press('Control+z');const changed=(await state()).html!==before;if(changed){await page.keyboard.press('Control+y');if((await state()).html!==before)throw failure('UNDO_REDO_EQUIVALENCE',JSON.stringify({before,after:(await state()).html}));}}
 else if(a.kind==='copy'){await select(a);const before=(await state()).html;await page.evaluate(()=>{const d=new DataTransfer();document.querySelector('.editor-content').dispatchEvent(new ClipboardEvent('copy',{bubbles:true,cancelable:true,clipboardData:d}));window.audit.lastCopy={html:d.getData('text/html'),text:d.getData('text/plain')};});if((await state()).html!==before)throw failure('COPY_MUTATES','Copy changed document');}
 else if(a.kind==='cut'){await select(a);await page.keyboard.press('Control+x');}
 else if(a.kind==='ctrlClick'){await page.locator('.editor-content p').nth(a.block%await page.locator('.editor-content p').count()).evaluate(e=>{e.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,ctrlKey:true,button:0,buttons:1}));e.dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:true}));});await page.keyboard.press('Escape');}
 else if(a.kind==='navigate'){await page.locator('.editor-content').evaluate(e=>e.dispatchEvent(new FocusEvent('blur',{bubbles:true})));await page.waitForTimeout(450);const old=(await state()).semantic;await page.locator('#visit').click();await page.waitForTimeout(35);await page.locator('#visit').click();await page.waitForTimeout(35);if((await state()).semantic!==old)throw failure('NODE_ROUNDTRIP','Node switch changed serialized content');}
 else if(a.kind==='remount'){await page.locator('.editor-content').evaluate(e=>e.dispatchEvent(new FocusEvent('blur',{bubbles:true})));await page.waitForTimeout(450);const before=await state();const html=before.html;await reset(html);if((await state()).semantic!==before.semantic)throw failure('DOM_ROUNDTRIP','Remount changed serialized content');}
 await invariant();
}
const texts=['x','á','😀','👨‍👩‍👧‍👦','e\u0301','中文','日本語','مرحبا','https://ejemplo.test/a?b=2','A & B','<literal>',' > símbolo'];
function generate(seed,length){const random=rng(seed),pick=xs=>xs[Math.floor(random()*xs.length)],result=[];for(let i=0;i<length;i++){const common={block:Math.floor(random()*25),textIndex:0,start:Math.floor(random()*8),end:8+Math.floor(random()*8)};const kind=pick(['replace','replace','type','key','mark','paste','select','copy','cut','undoRedo','ctrlClick','navigate','remount']);const a={...common,kind};if(kind==='replace'||kind==='type')a.value=pick(kind==='replace'?texts.filter(t=>!t.trimStart().startsWith('>')):texts);if(kind==='key')a.key=pick(['Enter','Shift+Enter','Backspace','Delete','Home','End','ArrowLeft','ArrowRight','ArrowUp','ArrowDown']);if(kind==='mark')a.key=pick(['Control+b','Control+i','Control+u']);if(kind==='paste'){a.html=random()<.5;a.value=a.html?pick(['<p><b>bold</b> <u>under</u></p>','<h2>Título</h2><ul><li>uno</li><li>dos</li></ul>','<p>&lt;literal&gt; &amp; &quot;quote&quot;</p>','<table><tr><td>中文</td><td>😀</td></tr></table>','<p>antes <span data-mention-id="B">Nodo B</span> después</p>']):pick(texts)+'\nsegundo';}if(kind==='select')a.cross=random()<.4;result.push(a);}return result;}
async function execute(seed,actions,{record=true}={}){await reset();const trace=[];let failed=null;for(let i=0;i<actions.length;i++){const before=await state(),started=performance.now();try{await action(actions[i]);trace.push({index:i,action:actions[i],before,after:await state(),ms:performance.now()-started});}catch(e){const currentFailure={id:e.auditId??'HARNESS_EXCEPTION',message:e.message,stack:e.stack,index:i};failed??=currentFailure;trace.push({index:i,action:actions[i],before,after:await state(),exception:currentFailure});if(arg('explore','0')!=='1')break;}}if(record){await writeFile(`${dir}/seed-${seed}-${++serial}.json.gz`,gzipSync(JSON.stringify({seed,actions,trace,failed,errors,warnings}),{level:9}));runs.push({seed,requested:actions.length,executed:trace.length,failed});}return failed;}
async function shrink(seed,actions,id){let current=actions.slice(),n=2,attempts=0;while(current.length>1&&attempts<65){let reduced=false;const size=Math.ceil(current.length/n);for(let i=0;i<current.length&&attempts<65;i+=size){const candidate=current.slice(0,i).concat(current.slice(i+size));if(!candidate.length)continue;attempts++;const f=await execute(seed,candidate,{record:false});if(f?.id===id){current=candidate;n=Math.max(2,n-1);reduced=true;break;}}if(!reduced){if(n>=current.length)break;n=Math.min(current.length,n*2);}}return {actions:current,attempts};}
async function regression(name,fn){await reset();try{await fn();await invariant();regressions.push({name,status:'pass'});}catch(e){regressions.push({name,status:'fail',error:e.message});findings.push({id:`REG_${name}`,seed:0,message:e.message,actions:[],state:await state()});}}
try{
 await server.listen();browser=await chromium.launch({channel:'msedge',headless:true});page=await browser.newPage();page.setDefaultTimeout(30000);
 await page.addInitScript(()=>{const timeouts=new Set(),intervals=new Set(),urls=new Set();const st=window.setTimeout.bind(window),ct=window.clearTimeout.bind(window),si=window.setInterval.bind(window),ci=window.clearInterval.bind(window);window.setTimeout=(fn,delay,...args)=>{if(typeof fn!=='function')return st(fn,delay,...args);let id=st(()=>{timeouts.delete(id);fn(...args);},delay);timeouts.add(id);return id;};window.clearTimeout=id=>{timeouts.delete(id);ct(id);};window.setInterval=(fn,delay,...args)=>{const id=si(fn,delay,...args);intervals.add(id);return id;};window.clearInterval=id=>{intervals.delete(id);ci(id);};const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=b=>{const u=create(b);urls.add(u);return u;};URL.revokeObjectURL=u=>{urls.delete(u);revoke(u);};window.auditResources=()=>({timeouts:timeouts.size,intervals:intervals.size,objectUrls:urls.size});});
 page.on('pageerror',e=>errors.push(e.stack??e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))warnings.push({type:m.type(),text:m.text()});});
 await page.goto(`http://127.0.0.1:${auditPort}/audit`,{waitUntil:'domcontentloaded',timeout:120000});await page.locator('[data-test="p50"]').waitFor({timeout:120000});console.log('AUDIT ready');
 if(arg('skip-regressions','0')!=='1'){
 await regression('ctrlClick-scroll-multiselect',async()=>{await page.locator('#scroll').evaluate(e=>e.scrollTop=1600);for(const i of [50,51,52,51]){await page.locator(`[data-test="p${i}"]`).evaluate(e=>{e.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,ctrlKey:true,button:0,buttons:1}));e.dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:true}));});assert.equal((await state()).scroll,1600);}assert.deepEqual(await page.locator('[data-line-selected]').evaluateAll(es=>es.map(e=>e.getAttribute('data-test'))),['p50','p52']);});
 await regression('H1-selection',async()=>{await page.locator('h1').dblclick();await page.waitForTimeout(150);assert.ok((await state()).selection.text.length);});
 await regression('back-forward-scroll',async()=>{await page.locator('#scroll').evaluate(e=>e.scrollTop=1800);await page.locator('#visit').click();await page.waitForTimeout(50);await page.locator('#scroll').evaluate(e=>e.scrollTop=900);await page.locator('#back').click();await page.waitForTimeout(80);assert.equal((await state()).scroll,1800);await page.locator('#forward').click();await page.waitForTimeout(80);assert.equal((await state()).scroll,900);});
 await regression('paste-full-partial-html',async()=>{await action({kind:'replace',block:1,start:0,end:999,value:'123'});await action({kind:'replace',block:2,start:8,end:14,value:'中文😀'});await select({block:3,start:0,end:5});await paste('<strong>NEW</strong>',true);assert.match((await state()).blocks[3].text.replace(/\u00a0/g,' '),/NEW 2 abcdef/);});
 await regression('marks-toolbar-mention',async()=>{await reset('<p><u>antes <span class="editor-mention" data-mention-id="B" contenteditable="false">Nodo B</span> después</u></p>');await select({block:0,start:0,end:4});await page.waitForTimeout(80);const marks=await page.evaluate(()=>window.audit.readInlineMarkState(getSelection().getRangeAt(0),document.querySelector('.editor-content')));assert.equal(marks.underline,'on');await page.locator('[data-selection-toolbar]').waitFor();await page.keyboard.press('Control+b');assert.equal(await page.locator('[data-mention-id="B"]').count(),1);await action({kind:'replace',block:0,start:0,end:1,value:'X'});assert.equal(await page.locator('[data-mention-id="B"]').count(),1);});
 await regression('toolbar-on-off-mixed-and-strike',async()=>{await reset('<p><u>uno</u> dos</p>');await select({block:0,start:0,end:3});await page.waitForTimeout(60);assert.equal(await page.locator('[data-selection-toolbar] button').nth(2).getAttribute('data-mark-state'),'on');await page.evaluate(()=>{const e=document.querySelector('.editor-content'),r=document.createRange();r.selectNodeContents(e.firstElementChild);getSelection().removeAllRanges();getSelection().addRange(r);});await page.waitForTimeout(60);assert.equal(await page.locator('[data-selection-toolbar] button').nth(2).getAttribute('data-mark-state'),'mixed');await page.locator('[data-selection-toolbar] button').nth(3).click();await page.waitForTimeout(60);assert.equal(await page.locator('[data-selection-toolbar] button').nth(3).getAttribute('data-mark-state'),'on');});
 await regression('slash-headings-list',async()=>{for(const [label,tag] of [[/^(Título 1|Heading 1)$/,'h1'],[/^(Lista con viñetas|Bulleted list)$/,'li']]){await reset('<p><br></p>');await page.locator('.editor-content p').click();await page.keyboard.type('/');await page.locator(`[data-picker-menu-item="${tag==='h1'?'h1':'ul'}"]`).click();await page.keyboard.insertText('Contenido 😀');assert.ok(await page.locator('.editor-content '+tag).count());assert.match((await state()).text,/Contenido 😀/);await action({kind:'undoRedo'});}});
 await regression('table-runtime-roundtrip',async()=>{const html=await page.evaluate(()=>window.audit.createTable(500).outerHTML);await reset(html+'<p>final</p>');const count=await page.locator('[data-his-table-cell]').count();assert.equal(count,9);await page.evaluate(()=>{const cells=document.querySelectorAll('[data-his-table-cell]');cells.forEach((cell,i)=>{cell.querySelector('p').textContent=`celda ${i} 中文😀`;});});const initial=(await state()).html;for(let i=0;i<5;i++){await reset(initial);assert.equal(await page.locator('[data-his-table-cell]').count(),9);assert.equal((await state()).html,initial);assert.equal(await page.locator('[data-his-table-handle="cell"]').count(),9);}});
 await regression('ctrlA-copy-delete-undo',async()=>{const initial=(await state()).html;await page.locator('.editor-content').focus();await page.keyboard.press('Control+a');assert.ok(await page.locator('[data-line-selected]').count()>90||(await state()).selection?.text.includes('Block 99 abcdef'));await page.evaluate(()=>{const d=new DataTransfer();document.querySelector('.editor-content').dispatchEvent(new ClipboardEvent('copy',{bubbles:true,cancelable:true,clipboardData:d}));window.audit.lastCopy=d.getData('text/html');});assert.doesNotMatch(await page.evaluate(()=>window.audit.lastCopy),/data-line-selected|data-editor-ui/);await page.keyboard.press('Delete');assert.ok((await state()).text.length<100);await page.keyboard.press('Control+z');await page.waitForTimeout(100);await invariant();await reset((await state()).html);await invariant();assert.equal((await state()).html,initial);});
 await regression('node-drop-mention-undo',async()=>{await page.locator('[data-test="p0"]').scrollIntoViewIfNeeded();const box=await page.locator('[data-test="p0"]').boundingBox();await page.evaluate(({x,y})=>{const d=new DataTransfer();d.setData('application/x-hisfuture-node','B');document.querySelector('.editor-content').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:d,clientX:x,clientY:y}));},{x:box.x+10,y:box.y+10});assert.ok(await page.locator('[data-mention-id="B"]').count()>=2);await action({kind:'undoRedo'});});
 }
 const count=Number(arg('properties',3000));const propertyResults=await page.evaluate(({count,texts})=>{const failures=[],a=window.audit;let checks=0;function check(id,seed,input,expected,actual){checks++;if(expected!==actual&&!failures.some(x=>x.id===id))failures.push({id,seed,input,expected,actual});}for(let seed=1;seed<=count;seed++){const text=texts[seed%texts.length]+` / ${seed} & < > " '`;const esc=text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const input=`<p data-line-selected="true" contenteditable="false">${esc}<span data-editor-ui="true"><b>UI</b></span></p>`;const stripped=a.stripTransientEditorState(input);check('SERIALIZATION_IDEMPOTENCY',seed,input,stripped,a.stripTransientEditorState(stripped));const d=document.createElement('div');d.innerHTML=stripped;check('SERIALIZATION_TEXT',seed,input,text,d.textContent);const clean=a.sanitizeEditorHtml(`<p>${esc}</p>`);d.innerHTML=clean;check('SANITIZE_TEXT',seed,`<p>${esc}</p>`,text,d.textContent);const formatted=a.formatPastedText(text);d.innerHTML=a.sanitizeEditorHtml(formatted);check('PLAIN_PASTE_TEXT',seed,text,text,d.textContent);d.innerHTML=a.sanitizeEditorHtml('<p onclick="alert(1)">safe<script>bad</script><a href="javascript:alert(1)">link</a></p>');check('SANITIZER_UNSAFE_ATTRIBUTES',seed,'onclick/javascript/script',0,d.querySelectorAll('[onclick],script,[href^="javascript:"]').length);const transfer=new DataTransfer();transfer.setData('text/plain',`a\t${seed}\n中文\t😀`);check('TABLE_TSV',seed,String(seed),JSON.stringify([['a',String(seed)],['中文','😀']]),JSON.stringify(a.clipboardToMatrix(transfer)));}return {checks,failures};},{count,texts});properties.push(propertyResults);findings.push(...propertyResults.failures);console.log('PROPERTIES',propertyResults.checks,'unique failures',propertyResults.failures.length);
 const replay=arg('replay',null);const specs=arg('only-focus','0')==='1'?[]:replay?[{seed:(await readJson(replay)).seed,actions:(await readJson(replay)).actions}]:arg('seed',null)?[{seed:Number(arg('seed',0)),length:Number(arg('length',400))}]:[{seed:938271,length:20},{seed:20261002,length:80},{seed:347,length:200},{seed:731993,length:500},{seed:17,length:1000}];
 for(const spec of specs){const actions=spec.actions??generate(spec.seed,spec.length);const f=await execute(spec.seed,actions);console.log('SEQUENCE',spec.seed,actions.length,f?.id??'pass');if(f&&!findings.some(x=>x.id===f.id)){const confirmed=await execute(spec.seed,actions,{record:false});if(confirmed?.id===f.id){const minimized=await shrink(spec.seed,actions.slice(0,f.index+1),f.id);const item={...f,seed:spec.seed,...minimized,confirmed:true};findings.push(item);await writeFile(`tests/editor-audit/corpus-${f.id}.json`,JSON.stringify(item,null,2));console.log('SHRUNK',f.id,minimized.actions.length,minimized.attempts);}}}
 if(arg('skip-soak','0')!=='1'){
 await regression('large-input-remount',async()=>{for(const text of ['','x','😀'.repeat(50000),Array.from({length:1500},(_,i)=>`p${i}`).join('\n')]){const html=await page.evaluate(text=>window.audit.formatPastedText(text),text);await reset(html);const first=(await state()).html;for(let i=0;i<3;i++){await reset(first);assert.equal((await state()).html,first);}}});
 await reset();const cdp=await page.context().newCDPSession(page);for(let batch=0;batch<8;batch++){const times=[];for(let i=0;i<20;i++){const t=performance.now();await reset();await select({block:1,start:0,end:5});await paste('abc');times.push(performance.now()-t);}await cdp.send('HeapProfiler.collectGarbage');const metrics=(await cdp.send('Performance.getMetrics')).metrics;const counters=await cdp.send('Memory.getDOMCounters');const usage=await cdp.send('Runtime.getHeapUsage');times.sort((a,b)=>a-b);soak.push({batch,heap:usage.usedSize,...counters,p50:times[10],p95:times[18],renders:await page.evaluate(()=>window.audit.getRenders()),resources:await page.evaluate(()=>window.auditResources()),metrics});console.log('SOAK',batch,usage.usedSize,counters.jsEventListeners,times[18]);}
 }
}catch(e){findings.push({id:'HARNESS_FATAL',message:e.message,stack:e.stack});console.error(e);}finally{
 const unchanged=JSON.stringify(baseline)===JSON.stringify(await hashes());const report={timestamp:new Date().toISOString(),productionUnchanged:unchanged,runs,regressions,properties,findings,soak,errors,warnings};await writeFile(`${dir}/report.json`,JSON.stringify(report,null,2));console.log('REPORT',JSON.stringify({unchanged,runs:runs.map(({seed,requested,executed,failed})=>({seed,requested,executed,failed:failed?.id})),regressions,findings:findings.map(x=>({id:x.id,seed:x.seed,actions:x.actions?.length})),errors}));await browser?.close();await server.close();if(!unchanged)process.exitCode=2;else if(findings.some(x=>x.id==='HARNESS_FATAL'))process.exitCode=1;else if(arg('strict','0')==='1'&&findings.length)process.exitCode=1;
}
